### ISSUE TITLE
App crashes during certain resizing operations

### ISSUE THREAD

**Issue by ghost** [jrprice/NBody-Metal#2]
I've found that I can cause the app to crash consistently with the key sequence `+---+`. (this may vary by hardware). It appears that the `memcpy` on [L223](https://github.com/jrprice/NBody-Metal/blob/master/NBody-Metal/NBodyViewController.swift#L223) and [L227](https://github.com/jrprice/NBody-Metal/blob/master/NBody-Metal/NBodyViewController.swift#L227) of NBodyViewController.swift can read past the bounds of the buffers from which the old data is copied. Memcpying only the min of the current and previous dataSize seems to fix the problem.

**Comment by jrprice** [comment]
Thanks - should be fixed in 8f742dd.
